number = float(input('Digite um numero pra mostrar sua tabuada: '))

print('{:.2f} x 1 = {:.2f}'.format(number, number * 1))
print('{:.2f} x 2 = {:.2f}'.format(number, number * 2))
print('{:.2f} x 3 = {:.2f}'.format(number, number * 3))
print('{:.2f} x 4 = {:.2f}'.format(number, number * 4))
print('{:.2f} x 5 = {:.2f}'.format(number, number * 5))
print('{:.2f} x 6 = {:.2f}'.format(number, number * 6))
print('{:.2f} x 7 = {:.2f}'.format(number, number * 7))
print('{:.2f} x 8 = {:.2f}'.format(number, number * 8))
print('{:.2f} x 9 = {:.2f}'.format(number, number * 9))
print('{:.2f} x 10 = {:.2f}'.format(number, number * 10))
